apiVersion: v1
kind: ConfigMap
metadata:
  name: fuseagent-console
data:
  API_SERVER_ENDPOINT: http://localhost:8000
  API_SERVER_BASE_PATH: /api/v1
  NEXT_PUBLIC_DEFAULT_LOCALE: zh-CN
  NEXT_PUBLIC_APP_NAME: fuseAgent
